name: "Deploy To Netlify"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - "main"

env:
  BUILD_DRAFTS: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy To Netlify"
    steps:
      - uses: actions/checkout@v2
      - run: "git log --pretty=oneline"
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy to v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: npm install
          build_command: npm run build
          build_directory: "_site"
